### ISSUE TITLE
BF 3.2: blackbox log corrupted

### ISSUE THREAD

**Issue by mluessi** [BrainFPV/betaflight#16]
Blackbox logs cannot be read by BB explorer

v3.2.0-RC3-BRAIN-1

**Comment by Zytrahus** [comment]
Thanks for creating this ticket, were you able to replicate the issue on your side since I emailed you about it?

I tried logging again last night with various logging speed and same results.
Also not sure if you noticed but the log's header is repeated 10+ times instead of having it just once...

edit: https://github.com/betaflight/betaflight/issues/3917#issuecomment-324972164

Cheers

**Comment by Zytrahus** [comment]
Hello,
I installed 3.2 BRAIN-1 on 2 quads and have the same issues about the logs being unreadable by BBexplorer.

Thanks
